version: "3"

services:
  election_database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - election_volume:/var/lib/mysql
    networks:
      - admin_network

  election_database_migration:
    image: election_database_migration
    environment:
      - DATABASE_URL=election_database
    networks:
      - admin_network
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    image: redis
    networks:
      - voting_station_network

  admin_service:
    image: admin
    environment:
      - DATABASE_URL=election_database
    ports:
      - 5001:5001
    networks:
      - admin_network

  daemon_service:
    image: daemon
    environment:
      - REDIS_URL=redis
      - DATABASE_URL=election_database
    networks:
      - voting_station_network
      - admin_network

  voting_station_service:
    image: voting_station
    environment:
      - REDIS_URL=redis
    ports:
      - 5002:5002
    networks:
      - voting_station_network
    deploy:
      replicas: 3

volumes:
  election_volume:

networks:
  admin_network:
    driver: overlay
  voting_station_network:
    driver: overlay