version: "3"

services:
  authentication_database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - authentication_volume:/var/lib/mysql
    networks:
      - authentication_network

  authentication_database_migration:
    image: authentication_database_migration
    environment:
      - DATABASE_URL=authentication_database
    networks:
      - authentication_network

  authentication_service:
    image: authentication
    environment:
      - DATABASE_URL=authentication_database
    ports:
      - 5000:5000
    networks:
      - authentication_network

volumes:
  authentication_volume:

networks:
  authentication_network: